all:
		g++ -o q1 question1_soln.cpp;
		g++ -o q2 question2_soln.cpp;
		g++ -o q3 question3_soln.cpp
		g++ -o q4 question4_soln.cpp;
		g++ -o q5 question5_soln.cpp;
		g++ -o q6a question6a_soln.cpp;
		g++ -o q6b question6b_soln.cpp
clean:
		$(RM) q1
		$(RM) q2
		$(RM) q3
		$(RM) q4
		$(RM) q5
		$(RM) q6a
		$(RM) q6b